### ISSUE TITLE
Submission Review

### ISSUE THREAD

**Issue by ivan-adakerja** [sulthonmb/chatbot-nodejs-with-dialogflow#3]
Hi @sulthonmb ! I am Ivan from AdaKerja 😄 👋
Thank you for your submission, what a fancy submission you have here 👍 

Anyway have some questions / requests:

- Could you add some record / .gif showing bot working?
- Could you walk us through the code? How user able to connect between each questions? 
ex. from 'UserName' to 'UserBorn'? or the part to process user want (/ doesn't want) to know the birthday?
- So I run the test `yarn test` and I receive this.I want to check for routes but it ask for .env. What do you think the issue here?

 ```
 FAIL  src/routes.test.js
  ● Test suite failed to run

    Invariant Violation: Facebook access token is required. Please make sure you have filled it correctly in `bottender.config.js` or `.env` file.

      14 |   dev: process.env.NODE_ENV !== 'production',
      15 | });
    > 16 | const client = getClient('messenger');
         |                ^
      17 |
      18 | const port = Number(process.env.PORT) || 5000;
      19 |

      at Object.invariant [as default] (node_modules/invariant/invariant.js:40:15)
      at new FacebookBaseConnector (node_modules/bottender/src/messenger/FacebookBaseConnector.ts:73:16)
      at new MessengerConnector (node_modules/bottender/src/messenger/MessengerConnector.ts:39:5)
      at new MessengerBot (node_modules/bottender/src/messenger/MessengerBot.ts:29:23)
      at getClient (node_modules/bottender/src/shared/getClient.ts:56:22)
      at Object.<anonymous> (server.js:16:16)
```

**Comment by sulthonmb** [comment]
Hallo @ivan-adakerja 👋
Thank you for your response and feedback. Anyway for your questions:

1. I attach a video recording for the Facebook message bot, if you want to try I need your Facebook ID so I can add your account as a tester on my Facebook app. I cannot change the mode to live, because the regulation of Facebook is required to verify the business. Look at the video via [this link](https://drive.google.com/file/d/1hfNq12X2nV7hf4Epwq3_FlptXlvpKARf/view?usp=sharing).
2. The app will receive every message via webhook and throw the message on https://github.com/sulthonmb/chatbot-nodejs-with-dialogflow/blob/93ed8bfe9c1531f0d2f2e30961faec5ac1c94a7b/src/index.js#L32-L38 If the messages are not included on GET_STARTED it will forward the message to Dialogflow. Dialogflow will try to understand the messages and decide the message include which intents. 
![image](https://user-images.githubusercontent.com/22268226/149774166-ea9d8bfb-8e29-4301-8aaa-b167198801f6.png) After that if the intent does not require a webhook, Dialogflow will send the response to the chatbot and give the response to the user. But if the intent does require a webhook like this <img width="797" alt="Screenshot 2022-01-17 at 21 05 36" src="https://user-images.githubusercontent.com/22268226/149774771-761e718d-df9b-45ae-a4b9-7dac92564f20.png"> Dialogflow will request webhook to the chatbot on this part https://github.com/sulthonmb/chatbot-nodejs-with-dialogflow/blob/93ed8bfe9c1531f0d2f2e30961faec5ac1c94a7b/src/services/dialogflow/index.js#L1-L44 So the chatbot will know the messages are included on what intent, so the chatbot is able to do some process like record new data raw on the database, calculate, etc. After that, the chatbot will send responses to the user https://github.com/sulthonmb/chatbot-nodejs-with-dialogflow/blob/93ed8bfe9c1531f0d2f2e30961faec5ac1c94a7b/src/services/dialogflow/userName.js#L22-L40
3. You need to create an env file for the app. I think, you will be hard to implement Dialogflow, if you want to try I can send my credentials and env file via email. For the test, it will look like this 
![image](https://user-images.githubusercontent.com/22268226/149776261-6066a1f0-798a-42f9-a3fb-217a04936e1c.png)
